name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "false"
          LOCALE: "zh"
          COMMIT_MESSAGE: "我又在写代码了"
          COMMIT_USERNAME: "MoeJue"
          SHOW_TIMEZONE: "Asia/Shanghai"
          SHOW_LINES_OF_CODE: "false"
          UPDATED_DATE_FORMAT: "%Y-%m-%d %H:%M:%S"
          SHOW_SHORT_INFO: "false"
          COMMIT_EMAIL: "32321958+iAJue@users.noreply.github.com"
